spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone:
        http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true
