spring:
  application:
    name: woobeee-gateway
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: debug

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone:
        http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true