server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: woobeee-gateway
  profiles:
    default: prod
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: auth
          uri:
            lb://WOOBEEE-AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: blog
          uri: lb://WOOBEEE-BLOG
          predicates:
            - Path=/api/v1/blog/**
          filters:
            - AuthorizationFilter

  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc

logging:
  level:
    root: debug




